### PR TITLE
ST3 support

### PR DESCRIPTION
**Pull request by nahaylo**

### CODE REVIEW

**Comment by luqman** [comment]
@nahaylo happy to merge, does it still work with ST2? just don't want to break it for ST2 users if they upgrade the package.

**Comment by nahaylo** [comment]
@luqman I don't know. Unfortunately I don't have possibility to check. I"ve tested for ST3 only.

**Comment by nahaylo** [comment]
screen shot 2015-04-03 at 22 34 29
It's a screenshot for ST3

**Comment by luqman** [comment]
@nahaylo ok I installed ST2 and tested, its broken. Would be cool if we can keep ST2 working, I think its to do with the import statements. Not concerned about the Spanish inflector being removed. I'll try and take a look.

**Comment by luqman** [comment]
@nahaylo try this

```python

try:
  from .vendor.inflector import *
except ImportError:
  from vendor.inflector import *
```

So its trying to import using python 3 syntax first and then 2. If you can update the PR, I can test again.

**Comment by luqman** [comment]
Seen another plugin use something like this, probably better?
```python
if sys.version_info[0] == 2:
  from vendor.inflector import *
else:
  from .vendor.inflector import *
```

**Comment by nahaylo** [comment]
I think the last would be better.
Just figure out that one of my college at work uses ST2. Lets postpone till Monday. I'll fix and try on different version. 
Thanks for help.
BTW, I'm not aware of python as you, just want to make world better :)

**Comment by luqman** [comment]
@nahaylo no problem :) i too have extremely little python knowledge, right now mainly ember.js/ruby :)

**Comment by nahaylo** [comment]
Tested on ST3, works OK.
@luqman could you check if it works OK on ST2?

**Comment by luqman** [comment]
@nahaylo I'll give a test on Tuesday and get it merged if its all good.

did you try using conditionals (better) vs try/catch ?

**Comment by nahaylo** [comment]
Hi, for some reason it didn't want to work with `sys.version_info`
and works ok with try/catch

**Comment by luqman** [comment]
@nahaylo ok it appears to be working fine. merged, thanks

**Pull request merged**
